"""empty message

Revision ID: 2621007c6faa
Revises: 3235153b6df0
Create Date: 2020-08-08 00:36:47.162478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2621007c6faa'
down_revision = '3235153b6df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('zipcode', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_type')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('zipcode', sa.Integer(), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('profile_image', sa.String(length=500), nullable=False),
    sa.Column('about_me', sa.String(length=1000), nullable=False),
    sa.Column('subjects_needed', sa.String(length=120), nullable=False),
    sa.Column('current_grade', sa.String(length=120), nullable=False),
    sa.Column('wkly_hrs_needed', sa.String(length=120), nullable=False),
    sa.Column('grades_tutored', sa.String(length=120), nullable=False),
    sa.Column('subjects_tutored', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    op.drop_table('user_account')
    # ### end Alembic commands ###
